services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run dev
    volumes:
      - ./frontend:/usr/local/app
      - /usr/local/app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: uv run python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/usr/local/app
      - /usr/local/app/.env
